FROM astral/uv:python3.12-bookworm-slim

# Install system dependencies, including libexpat1
RUN apt-get update && apt-get install -y --no-install-recommends \
    libexpat1 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /geojson
COPY ./services/fetch_load_data/geojson/gadm41_SLV_0.geojson /geojson/gadm41_SLV_0.geojson
COPY ./services/fetch_load_data/geojson/gadm41_SLV_1.geojson /geojson/gadm41_SLV_1.geojson

RUN mkdir -p /config/api_keys
COPY pib-geoespacial-3ba5fc82e62c.json /config/api_keys

COPY ./services/fetch_load_data/blackmarblepy_dist /blackmarblepy_dist
COPY ./services/fetch_load_data/tasks /tasks 
COPY ./services/fetch_load_data/tasks/utils /tasks/utils 
COPY ./services/fetch_load_data/pyproject.toml /pyproject.toml
COPY ./services/fetch_load_data/uv.lock /uv.lock
COPY ./services/fetch_load_data/.python-version /.python-version

RUN uv sync 