[project]
name = "pipeline-data-slv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "blackmarblepy>=2025.11.2",
    "earthengine-api>=1.7.19",
    "fredapi>=0.5.2",
    "geopandas>=1.1.3",
    "ipython>=9.12.0",
    "polars[all]>=1.39.3",
]

[tool.uv.workspace]
members = [
    "services/streamlit_app",
    "services/models",
]
