FROM astral/uv:python3.12-bookworm-slim

# Copiamos codebase
COPY ./services/streamlit_app/cov_administrativas /cov_administrativas
COPY ./services/streamlit_app/cov_geoespaciales /cov_geoespaciales
COPY ./services/streamlit_app/cov_subnacional /cov_subnacional
COPY ./services/streamlit_app/metadata /metadata
COPY ./services/streamlit_app/pages /pages
COPY ./services/streamlit_app/utils /utils

COPY ./services/streamlit_app/streamlit_app.py /streamlit_app.py

# Sincronizamos el proyecto uv
COPY ./services/streamlit_app/pyproject.toml /pyproject.toml
COPY ./services/streamlit_app/.python-version /.python-version
RUN uv sync 

ENTRYPOINT ["uv", "run", "streamlit", "run", "streamlit_app.py", "--server.port", "8502"]