FROM astral/uv:python3.12-bookworm-slim

# Define the R version you want
ARG R_VERSION=4.2.2.20221110-2

## Copia configuración de Python
RUN mkdir -p /config/api_keys
COPY pronosticos-493700-56f57502ffb3.json /config/api_keys
COPY ./services/subnacional/pyproject.toml /pyproject.toml
COPY ./services/subnacional/uv.lock /uv.lock
COPY ./services/subnacional/.python-version /.python-version
RUN uv sync 

## Instala R
# 2. Pin and install specific R components
# Note: You may need to add the CRAN repository first if the version isn't in default Debian repos
RUN apt-get update && apt-get install -y --no-install-recommends default-jre default-jdk\
    r-base-core=${R_VERSION} \
    r-base-dev=${R_VERSION} \
    r-recommended=${R_VERSION} \
    && rm -rf /var/lib/apt/lists/*
    
## The xlsx library in R requires Java Development Kit (JDK) as the package depends on rJava
RUN R CMD javareconf
## Instala dependencias de R
COPY ./services/subnacional/R_config.R /R_config.R 
RUN Rscript R_config.R

## Copia programas de la ejecución de la tarea
COPY ./services/subnacional/crea_pdata_bpvar.py /crea_pdata_bpvar.py 
COPY ./services/subnacional/bpvars.R /bpvars.R
COPY ./services/subnacional/envia_delta_lake.py /envia_delta_lake.py
COPY ./services/subnacional/envia_gs.py /envia_gs.py
COPY ./services/subnacional/utils /utils 

## Ejecuta tarea
COPY ./services/subnacional/run_subnacional.sh /run_subnacional.sh
RUN chmod +x run_subnacional.sh
ENTRYPOINT ["bash", "run_subnacional.sh"]

