[disaster_occurrence]
variable = "Ocurrencia de Desastres Naturales (EM-DAT)"
descripcion = "Ocurrencia de desastres naturales en El Salvador"
fuente = "https://www.emdat.be/"
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[dmsp_csm_sum]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[evi_gee]
variable = "EVI"
descripcion = "EVI (Enhanced Vegetation Index)"
fuente = "https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MOD09A1?hl=es-419"
frecuencia_actualizacion = "Semanal"
frecuencia_actualizacion_delta = "Cada 8 días"
rezago_fecha_actual = "Rezago de 1-2 semanas respecto a la fecha actual."

[ndbi_gee]
variable = "NDBI"
descripcion = "NDBI (Normalized Difference Built-up Index)"
fuente = "https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MOD09A1?hl=es-419"
frecuencia_actualizacion = "Semanal"
frecuencia_actualizacion_delta = "Cada 8 días"
rezago_fecha_actual = "Rezago de 1-2 semanas respecto a la fecha actual"

[ndvi_gee]
variable = "NDVI"
descripcion = "NDVI (Normalized Difference Vegetation Index)"
fuente = "https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MOD13Q1?hl=es-419#description"
frecuencia_actualizacion = "Bimensual"
frecuencia_actualizacion_delta = "Cada 16 días"
rezago_fecha_actual = ""

[ndvi_wfp]
variable = "NDVI (WFP)"
descripcion = "NDVI (Normalized Difference Vegetation Index)"
fuente = "https://data.humdata.org/dataset/slv-ndvi-subnational"
frecuencia_actualizacion = "Diario"
frecuencia_actualizacion_delta = "Cada 2 semanas"
rezago_fecha_actual = ""

[precip]
variable = "Precipitación"
descripcion = "Precipitacion (milímetros)"
fuente = "https://developers.google.com/earth-engine/datasets/catalog/UCSB-CHG_CHIRPS_PENTAD?hl=es-419#description"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Cada 5 días"
rezago_fecha_actual = "Rezago de 1-2 meses respecto a la fecha actual."

[temp_air]
variable = "Temperatura Aire ERA5"
descripcion = "Temperatura del aire (°C)"
fuente = "https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_LAND_MONTHLY_AGGR?hl=es-419"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Mensualmente"
rezago_fecha_actual = "Rezago de 1-2 meses respecto a la fecha actual"

[temp_ls]
variable = "Temperatura Superficie MODIS"
descripcion = "Temperatura de la superficie terrestre (°C)"
fuente = "https://developers.google.com/earth-engine/datasets/catalog/MODIS_061_MOD11A1?hl=es-419"
frecuencia_actualizacion = "Diario"
frecuencia_actualizacion_delta = "Diariamente"
rezago_fecha_actual = ""

[viirs_bm_sum]
variable = "VIIRS Black Marble"
descripcion = "Luces Nocturnas VIIRS Black Marble"
fuente = "https://viirsland-gsfc-nasa-gov.translate.goog/Products/NASA/BlackMarble.html?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Mensualmente"
rezago_fecha_actual = "Rezago de 1-4 meses respecto a la fecha actual. "
