[consumo_elect_al_publico]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[consumo_elect_comercio]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[consumo_elect_especiales]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[consumo_elect_industria]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[consumo_elect_residencial]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[consumo_elect_total]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[export_usd_fob]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[gdp_us_const_trim]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[import_usd_cif]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[indice_vol_encad]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[remesas_usd_trim]
variable = ""
descripcion = ""
fuente = ""
frecuencia_actualizacion = ""
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""
