[consumo_elect_al_publico]
variable = "Consumo electrico trimestral agregado al publico en kWh para El Salvador."
descripcion = "Consumo electrico trimestral agregado al publico en kWh para El Salvador."
fuente = "Datos administrativos compartidos"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Indefinido"
rezago_fecha_actual = ""

[consumo_elect_comercio]
variable = "Consumo electrico trimestral agregado a comercios en kWh para El Salvador."
descripcion = "Consumo electrico trimestral agregado a comercios en kWh para El Salvador."
fuente = "Datos administrativos compartidos"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Indefinido"
rezago_fecha_actual = ""

[consumo_elect_especiales]
variable = "Consumo electrico trimestral agregado a especiales en kWh para El Salvador."
descripcion = "Consumo electrico trimestral agregado a especiales en kWh para El Salvador."
fuente = "Datos administrativos compartidos"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Indefinido"
rezago_fecha_actual = ""

[consumo_elect_industria]
variable = "Consumo electrico trimestral agregado a industria en kWh para El Salvador."
descripcion = "Consumo electrico trimestral agregado a industria en kWh para El Salvador."
fuente = "Datos administrativos compartidos"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Indefinido"
rezago_fecha_actual = ""

[consumo_elect_residencial]
variable = "Consumo electrico trimestral agregado residencial en kWh para El Salvador."
descripcion = "Consumo electrico trimestral agregado residencial en kWh para El Salvador."
fuente = "Datos administrativos compartidos"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Indefinido"
rezago_fecha_actual = ""

[consumo_elect_total]
variable = "Consumo electrico trimestral agregado total en kWh para El Salvador."
descripcion = "Consumo electrico trimestral agregado total en kWh para El Salvador."
fuente = "Datos administrativos compartidos"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = "Indefinido"
rezago_fecha_actual = ""

[export_usd_fob]
variable = "Valor de exportaciones FOB en US$ trimestrales para El Salvador."
descripcion = "Valor de exportaciones FOB en US$ trimestrales para El Salvador."
fuente = "https://estadisticas.bcr.gob.sv/serie/ii-1-b-1-balanza-comercial-de-bienes-segun-ciiu-rev-4-valores-en-millones-de-us"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[gdp_us_const_trim]
variable = "GDP constante trimestral de EEUU."
descripcion = "GDP constante trimestral de EEUU."
fuente = "https://fred.stlouisfed.org/series/GDPC1"
frecuencia_actualizacion = "Trimestral"
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[import_usd_cif]
variable = "Valor de importaciones CIF en US$ trimestrales para El Salvador."
descripcion = "Valor de importaciones CIF en US$ trimestrales para El Salvador."
fuente = "https://estadisticas.bcr.gob.sv/serie/ii-1-b-1-balanza-comercial-de-bienes-segun-ciiu-rev-4-valores-en-millones-de-us"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[indice_vol_encad]
variable = "Indice de Volumen Encadenado"
descripcion = "PIB, Índices de volumen encadenados. Serie desestacionalizada (referencia 2014)."
fuente = "https://estadisticas.bcr.gob.sv/serie/pib-t-produccion-y-gasto-indices-de-volumen-encadenados-serie-desestacionalizada-referencia-2014-indices-de-volumen-encadenado"
frecuencia_actualizacion = "Trimestral"
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""

[remesas_usd_trim]
variable = "Remesas trimestrales en millones de US$ para El Salvador."
descripcion = "Remesas trimestrales en millones de US$ para El Salvador."
fuente = "https://estadisticas.bcr.gob.sv/serie/ingresos-mensuales-de-remesas-familiares"
frecuencia_actualizacion = "Mensual"
frecuencia_actualizacion_delta = ""
rezago_fecha_actual = ""
